import { useEffect, useState } from "react";
import type { Screen } from "../App";
import { apiClient } from "../lib/apiClient";
import { useAuth } from "../contexts/AuthContext";

type Pet = { id: string; name: string; species: string; breed: string | null; birth_date: string | null };
type Record = { id: string; record_type: string; occurred_on: string; notes: string | null; veterinarian: string | null; clinic: string | null };

export default function MedicalHistory({ navigate: _navigate }: { navigate: (s: Screen) => void }) {
  const { session } = useAuth();
  const [pets, setPets] = useState<Pet[]>([]); const [selectedPet, setSelectedPet] = useState<string>(""); const [records, setRecords] = useState<Record[]>([]);
  const [addingPet, setAddingPet] = useState(false); const [addingRecord, setAddingRecord] = useState(false); const [notice, setNotice] = useState("");
  const loadPets = async () => { if (!apiClient || !session) return; const { data } = await apiClient.from("personal_pets").select("id, name, species, breed, birth_date").order("name"); setPets(data ?? []); if (!selectedPet && data?.[0]) setSelectedPet(data[0].id); };
  useEffect(() => { void loadPets(); }, [session]);
  useEffect(() => { if (apiClient && selectedPet) apiClient.from("medical_records").select("id, record_type, occurred_on, notes, veterinarian, clinic").eq("pet_id", selectedPet).order("occurred_on", { ascending: false }).then(({ data }) => setRecords(data ?? [])); }, [selectedPet]);
  async function addPet(form: FormData) { if (!apiClient || !session) return; const { error } = await apiClient.from("personal_pets").insert({ owner_id: session.user.id, name: String(form.get("name")), species: String(form.get("species")), breed: String(form.get("breed")) || null, birth_date: String(form.get("birth_date")) || null }); if (error) setNotice("Não foi possível cadastrar o pet."); else { setAddingPet(false); setNotice("Pet cadastrado."); await loadPets(); } }
  async function addRecord(form: FormData) { if (!apiClient || !selectedPet) return; const { error } = await apiClient.from("medical_records").insert({ pet_id: selectedPet, record_type: String(form.get("record_type")), occurred_on: String(form.get("occurred_on")), veterinarian: String(form.get("veterinarian")) || null, clinic: String(form.get("clinic")) || null, notes: String(form.get("notes")) || null }); if (error) setNotice("Não foi possível salvar o registro."); else { setAddingRecord(false); setNotice("Registro salvo no prontuário."); const { data } = await apiClient.from("medical_records").select("id, record_type, occurred_on, notes, veterinarian, clinic").eq("pet_id", selectedPet).order("occurred_on", { ascending: false }); setRecords(data ?? []); } }
  const pet = pets.find((item) => item.id === selectedPet);
  return <div className="size-full overflow-y-auto bg-[#fdf6ee]"><div className="max-w-5xl mx-auto px-8 py-8"><div className="flex justify-between items-start mb-8"><div><h1 className="text-[#2d1f0f] text-3xl font-bold" style={{ fontFamily: "'Fraunces', serif" }}>Prontuário Digital</h1><p className="text-[#7a5c3f] text-sm mt-1">Histórico médico centralizado dos seus pets</p></div><button onClick={() => setAddingPet(true)} className="bg-[#efe5d8] text-[#2d1f0f] font-bold text-sm px-4 py-2.5 rounded-xl">+ Adicionar pet</button></div>
  {notice && <p className="mb-4 text-sm text-[#3d6b4f]">{notice}</p>}
  {addingPet && <Modal title="Cadastrar pet" close={() => setAddingPet(false)} onSubmit={addPet}><input name="name" required placeholder="Nome do pet" /><select name="species"><option value="dog">Cachorro</option><option value="cat">Gato</option><option value="other">Outro</option></select><input name="breed" placeholder="Raça" /><input name="birth_date" type="date" /></Modal>}
  {addingRecord && <Modal title={`Novo registro — ${pet?.name ?? "pet"}`} close={() => setAddingRecord(false)} onSubmit={addRecord}><input name="record_type" required placeholder="Tipo: vacina, consulta, exame…" /><input name="occurred_on" required type="date" /><input name="veterinarian" placeholder="Veterinário(a)" /><input name="clinic" placeholder="Clínica" /><textarea name="notes" placeholder="Observações" /></Modal>}
  <div className="grid grid-cols-3 gap-6"><aside className="bg-white rounded-2xl border border-[#e0cdb8] p-4"><p className="text-xs font-bold uppercase text-[#7a5c3f] mb-3">Meus pets</p>{pets.map((item) => <button key={item.id} onClick={() => setSelectedPet(item.id)} className={`w-full text-left p-3 rounded-xl mb-1 ${item.id === selectedPet ? "bg-[#fde8da] text-[#c4582a]" : "hover:bg-[#fdf6ee] text-[#2d1f0f]"}`}><b>{item.name}</b><span className="block text-xs mt-1">{item.species} · {item.breed ?? "SRD"}</span></button>)}{!pets.length && <p className="text-sm text-[#7a5c3f]">Você ainda não cadastrou nenhum pet.</p>}</aside><section className="col-span-2"><div className="flex justify-between items-center mb-4"><h2 className="text-xl font-bold text-[#2d1f0f]">{pet ? `Registros de ${pet.name}` : "Selecione um pet"}</h2>{pet && <button onClick={() => setAddingRecord(true)} className="bg-[#c4582a] text-white font-bold text-sm px-4 py-2.5 rounded-xl">+ Novo registro</button>}</div>{records.length ? <div className="space-y-3">{records.map((record) => <article key={record.id} className="bg-white rounded-2xl border border-[#e0cdb8] p-5"><div className="flex justify-between gap-4"><div><p className="font-bold text-[#2d1f0f]">{record.record_type}</p><p className="text-sm text-[#7a5c3f] mt-1">{record.veterinarian || "Profissional não informado"}{record.clinic ? ` · ${record.clinic}` : ""}</p>{record.notes && <p className="text-sm text-[#7a5c3f] mt-2">{record.notes}</p>}</div><time className="text-xs text-[#b8987a]">{new Intl.DateTimeFormat("pt-BR").format(new Date(`${record.occurred_on}T12:00:00`))}</time></div></article>)}</div> : pet && <p className="text-[#7a5c3f] text-sm">Nenhum registro ainda. Adicione a primeira passagem médica.</p>}</section></div></div></div>;
}
function Modal({ title, close, onSubmit, children }: { title: string; close(): void; onSubmit(form: FormData): void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 bg-black/30 grid place-items-center p-4"><form action={(form) => onSubmit(form)} className="w-full max-w-md bg-white rounded-2xl p-6 space-y-3"><h2 className="text-xl font-bold text-[#2d1f0f]">{title}</h2><div className="space-y-3 [&_input]:w-full [&_input]:border [&_input]:border-[#e0cdb8] [&_input]:rounded-xl [&_input]:p-3 [&_select]:w-full [&_select]:border [&_select]:border-[#e0cdb8] [&_select]:rounded-xl [&_select]:p-3 [&_textarea]:w-full [&_textarea]:border [&_textarea]:border-[#e0cdb8] [&_textarea]:rounded-xl [&_textarea]:p-3">{children}</div><div className="flex justify-end gap-2"><button type="button" onClick={close} className="px-4 py-2">Cancelar</button><button className="bg-[#c4582a] text-white font-bold px-4 py-2 rounded-xl">Salvar</button></div></form></div>; }
