import { useEffect, useState } from "react";
import type { Screen } from "../App";
import { apiClient } from "../lib/apiClient";
type Place = { id: string; name: string; description: string | null; address: string | null; city: string | null; phone: string | null; website: string | null; logo_url: string | null; latitude: number | null; longitude: number | null };
export default function NearbyMap({ navigate: _navigate }: { navigate: (s: Screen) => void }) {
  const [places, setPlaces] = useState<Place[]>([]); const [position, setPosition] = useState<{ latitude: number; longitude: number } | null>(null); const [selected, setSelected] = useState(""); const [status, setStatus] = useState("Solicitando sua localização…");
  useEffect(() => { void apiClient?.from("organizations").select("id,name,description,address,city,phone,website,logo_url,latitude,longitude").order("name").then(({ data }) => setPlaces((data ?? []) as Place[])); }, []);
  useEffect(() => { if (!navigator.geolocation) { setStatus("Geolocalização não disponível."); return; } const watch = navigator.geolocation.watchPosition(({ coords }) => { setPosition({ latitude: coords.latitude, longitude: coords.longitude }); setStatus("Sua localização atual"); }, () => setStatus("Permita sua localização para centralizar o mapa."), { enableHighAccuracy: true, maximumAge: 15000 }); return () => navigator.geolocation.clearWatch(watch); }, []);
  const lat = position?.latitude ?? -23.5505; const lng = position?.longitude ?? -46.6333; const mappable = places.filter((place) => place.latitude !== null && place.longitude !== null); const active = places.find((place) => place.id === selected);
  return <div className="size-full overflow-y-auto bg-[#fdf6ee]"><div className="mx-auto max-w-7xl px-4 py-5 sm:p-8"><div className="mb-5"><h1 className="text-2xl font-bold text-[#2d1f0f] sm:text-3xl" style={{ fontFamily: "'Fraunces', serif" }}>Perto de você</h1><p className="mt-1 text-sm text-[#7a5c3f]">📍 {status}</p></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]"><div className="relative min-h-[24rem] overflow-hidden rounded-2xl border border-[#e0cdb8]"><iframe title="Mapa navegável" className="absolute inset-0 h-full w-full border-0" src={`https://www.openstreetmap.org/export/embed.html?bbox=${lng - 0.025}%2C${lat - 0.018}%2C${lng + 0.025}%2C${lat + 0.018}&layer=mapnik&marker=${lat}%2C${lng}`} /><div className="pointer-events-none absolute inset-0">{mappable.map((place) => <button key={place.id} className="pointer-events-auto absolute -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#3d6b4f] px-2 py-1 text-sm shadow-lg" style={{ left: `${50 + ((Number(place.longitude) - lng) / .05) * 100}%`, top: `${50 - ((Number(place.latitude) - lat) / .036) * 100}%` }} onClick={() => setSelected(place.id)} aria-label={place.name}>🏢</button>)}</div><p className="absolute bottom-3 left-3 rounded-lg bg-white/90 px-3 py-2 text-xs text-[#7a5c3f]">Arraste o mapa para explorar. ONGs sem coordenadas não recebem marcador.</p></div><aside className="max-h-[32rem] space-y-3 overflow-y-auto">{!places.length ? <p className="rounded-2xl border border-dashed border-[#e0cdb8] bg-white p-5 text-sm text-[#7a5c3f]">Nenhuma ONG cadastrada ainda.</p> : places.map((place) => <button key={place.id} onClick={() => setSelected(place.id)} className={`w-full rounded-2xl border bg-white p-4 text-left ${selected === place.id ? "border-[#c4582a]" : "border-[#e0cdb8]"}`}><div className="flex gap-3"><img src={place.logo_url || "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=80&h=80&fit=crop"} alt="" className="h-11 w-11 rounded-xl object-cover" /><div className="min-w-0"><h2 className="truncate font-bold text-[#2d1f0f]">{place.name}</h2><p className="mt-1 text-xs text-[#7a5c3f]">📍 {[place.address, place.city].filter(Boolean).join(" · ") || "Endereço não informado"}</p></div></div></button>)}</aside></div>{active && <section className="mt-5 rounded-2xl border border-[#e0cdb8] bg-white p-5"><h2 className="font-bold text-[#2d1f0f]">{active.name}</h2><p className="mt-1 text-sm text-[#7a5c3f]">{active.description || "Sem descrição cadastrada."}</p><p className="mt-2 text-sm text-[#7a5c3f]">{active.phone && `📞 ${active.phone}`} {active.website && ` · ${active.website}`}</p></section>}</div></div>;
}
