import { useEffect, useState } from "react";
import { useAuth } from "../contexts/AuthContext";
import { apiClient } from "../lib/apiClient";
import { uploadImage } from "../lib/uploads";

type Form = { name: string; cnpj: string; email: string; phone: string; cep: string; address: string; neighborhood: string; city: string; state: string; website: string; description: string; logo_url: string };
const empty: Form = { name: "", cnpj: "", email: "", phone: "", cep: "", address: "", neighborhood: "", city: "", state: "", website: "", description: "", logo_url: "" };

export default function OrganizationProfile() {
  const { session, role } = useAuth(); const [form, setForm] = useState<Form>(empty); const [organizationId, setOrganizationId] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { if (apiClient && session && role === "organization") void apiClient.from("organizations").select("id, name, cnpj, email, phone, cep, address, neighborhood, city, state, website, description, logo_url").eq("owner_id", session.user.id).maybeSingle().then(({ data }) => { if (data) { setOrganizationId(data.id); setForm({ ...empty, ...data }); } }); }, [role, session]);
  if (role !== "organization") return <div className="p-6 text-[#7a5c3f]">Esta área é exclusiva para contas de ONG.</div>;
  const set = (key: keyof Form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function save(event: React.FormEvent) { event.preventDefault(); if (!apiClient || !session) return; const payload = { ...form, owner_id: session.user.id }; const result = organizationId ? await apiClient.from("organizations").update(payload).eq("id", organizationId).select("id").single() : await apiClient.from("organizations").insert(payload).select("id").single(); if (result.error) setNotice(result.error.message); else { setOrganizationId(result.data.id); setNotice("Dados da ONG salvos com sucesso."); } }
  const fields: [keyof Form, string, boolean][] = [['name','Nome da instituição/fantasia',true], ['cnpj','CNPJ',true], ['email','E-mail de contato',true], ['phone','Telefone',true], ['cep','CEP',true], ['address','Rua e número',true], ['neighborhood','Bairro',true], ['city','Cidade',true], ['state','Estado',true], ['website','Site ou rede social',false]];
  return <div className="size-full overflow-y-auto bg-[#fdf6ee]"><form onSubmit={save} className="mx-auto max-w-3xl px-4 py-5 sm:p-8"><h1 className="text-2xl font-bold text-[#2d1f0f] sm:text-3xl" style={{ fontFamily: "'Fraunces', serif" }}>Perfil da ONG</h1><p className="mb-6 mt-1 text-sm text-[#7a5c3f]">Essas informações ficam públicas nos animais vinculados.</p><div className="grid grid-cols-1 gap-4 rounded-2xl border border-[#e0cdb8] bg-white p-4 sm:grid-cols-2 sm:p-6">{fields.map(([key,label,required]) => <label key={key} className="min-w-0 text-sm font-bold text-[#7a5c3f]">{label}{required ? " *" : ""}<input required={required} value={form[key]} onChange={(event) => set(key, event.target.value)} className="mt-1 w-full rounded-xl border border-[#e0cdb8] p-3 font-normal text-[#2d1f0f]" /></label>)}<label className="min-w-0 text-sm font-bold text-[#7a5c3f]">Logo da instituição<input type="file" accept="image/*" className="mt-1 block w-full text-sm font-normal" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setNotice("Enviando logo…"); set("logo_url", await uploadImage(file, "organizations")); setNotice("Logo enviado. Salve o perfil para concluir."); } catch (error) { setNotice(error instanceof Error ? error.message : "Falha ao enviar logo."); } }} />{form.logo_url && <img src={form.logo_url} alt="Prévia do logo" className="mt-2 h-16 w-16 rounded-xl object-cover" />}</label><label className="text-sm font-bold text-[#7a5c3f] sm:col-span-2">Sobre a ONG *<textarea required rows={5} value={form.description} onChange={(event) => set("description", event.target.value)} className="mt-1 w-full rounded-xl border border-[#e0cdb8] p-3 font-normal text-[#2d1f0f]" /></label></div>{notice && <p className="mt-4 text-sm text-[#3d6b4f]" role="status">{notice}</p>}<button className="mt-6 rounded-xl bg-[#c4582a] px-5 py-3 font-bold text-white">Salvar perfil da ONG</button></form></div>;
}
