import { useEffect, useState } from "react";
import type { Screen } from "../App";
import { apiClient } from "../lib/apiClient";
import { useAuth } from "../contexts/AuthContext";
type Event = { id: string; title: string; starts_at: string; location: string; description: string | null; organizer_id: string | null };
export default function VaccinationEvents({ navigate: _navigate }: { navigate: (s: Screen) => void }) {
  const { session, role } = useAuth(); const [events, setEvents] = useState<Event[]>([]); const [form, setForm] = useState({ title: "", starts_at: "", location: "", description: "" }); const [notice, setNotice] = useState("");
  const load = async () => { if (!apiClient) return; const { data } = await apiClient.from("vaccination_events").select("id,title,starts_at,location,description,organizer_id").gte("starts_at", new Date().toISOString()).order("starts_at"); setEvents(data ?? []); };
  useEffect(() => { void load(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); if (!apiClient || !session) return; const { data: organization } = await apiClient.from("organizations").select("id").eq("owner_id", session.user.id).maybeSingle(); if (!organization) { setNotice("Salve primeiro o perfil da sua ONG."); return; } const { error } = await apiClient.from("vaccination_events").insert({ ...form, starts_at: new Date(form.starts_at).toISOString(), organizer_id: organization.id }); if (error) { setNotice(error.message); return; } setForm({ title: "", starts_at: "", location: "", description: "" }); setNotice("Evento publicado."); await load(); }
  return <div className="size-full overflow-y-auto bg-[#fdf6ee]"><div className="mx-auto max-w-5xl px-4 py-5 sm:p-8"><h1 className="text-2xl font-bold text-[#2d1f0f] sm:text-3xl" style={{ fontFamily: "'Fraunces', serif" }}>Eventos de vacinação</h1><p className="mt-1 text-sm text-[#7a5c3f]">Eventos publicados por ONGs e instituições parceiras.</p>{role === "organization" && <form onSubmit={create} className="mt-6 grid grid-cols-1 gap-3 rounded-2xl border border-[#e0cdb8] bg-white p-4 sm:grid-cols-2"><input required placeholder="Título do evento" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="rounded-xl border border-[#e0cdb8] p-3" /><input required type="datetime-local" value={form.starts_at} onChange={(e) => setForm({ ...form, starts_at: e.target.value })} className="rounded-xl border border-[#e0cdb8] p-3" /><input required placeholder="Localização" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} className="rounded-xl border border-[#e0cdb8] p-3 sm:col-span-2" /><textarea placeholder="Descrição, vacinas e orientações" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="rounded-xl border border-[#e0cdb8] p-3 sm:col-span-2" /><button className="w-fit rounded-xl bg-[#3d6b4f] px-4 py-3 text-sm font-bold text-white">Publicar evento</button></form>}{notice && <p className="mt-4 text-sm text-[#3d6b4f]">{notice}</p>}<div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{events.length ? events.map((item) => <article key={item.id} className="rounded-2xl border border-[#e0cdb8] bg-white p-5"><p className="text-xs font-bold text-[#3d6b4f]">💉 VACINAÇÃO</p><h2 className="mt-2 font-bold text-[#2d1f0f]">{item.title}</h2><p className="mt-2 text-sm text-[#7a5c3f]">📅 {new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.starts_at))}</p><p className="mt-1 text-sm text-[#7a5c3f]">📍 {item.location}</p><p className="mt-3 text-sm text-[#7a5c3f]">{item.description || "Sem informações adicionais."}</p></article>) : <p className="text-sm text-[#7a5c3f]">Nenhum evento publicado no momento.</p>}</div></div></div>;
}
